# Generated by Django 2.0.7 on 2018-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180827_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyaaan',
            old_name='nyan',
            new_name='echo',
        ),
    ]
